export default function DisclaimerPage() {
  return (
    <div className="bg-white text-gray-900 font-sans py-16 sm:py-20 px-4 sm:px-6 lg:px-8 max-w-4xl mx-auto space-y-10">
      
      {/* Header Section */}
      <div className="space-y-4 pt-4 sm:pt-6 border-b border-gray-200 pb-8">
        <h1 className="text-3xl sm:text-4xl font-extrabold tracking-tight text-gray-900">
          Disclaimer
        </h1>
        <p className="text-sm text-gray-500">
          Last Updated: September 2026
        </p>
      </div>

      {/* 1. Disclaimer Introduction */}
      <div className="space-y-4">
        <h2 className="text-xl font-bold text-gray-900">1. Disclaimer</h2>
        <p className="text-base text-gray-700 leading-relaxed">
          Welcome to <span className="font-semibold text-gray-900">CalculatePKTax</span> (accessible via <span className="font-semibold text-gray-900">calculatepktax.pk</span>). CalculatePKTax provides online tax calculation tools and general tax information strictly for informational and estimation purposes. By using our website, <span className="font-medium text-gray-900">tax calculator</span>, and associated pages, you acknowledge and agree to the terms of this Disclaimer.
        </p>
      </div>

      {/* 2. Tax Calculation Disclaimer */}
      <div className="space-y-3">
        <h2 className="text-xl font-bold text-gray-900">2. Tax Calculation Disclaimer</h2>
        <p className="text-base text-gray-700 leading-relaxed">
          Calculator results generated by our <span className="font-medium text-gray-900">Pakistan salary tax calculator</span> and <span className="font-medium text-gray-900">Pakistan income tax calculator</span> are estimates based on the selected tax year, salary information entered by the user, and the tax rules implemented on the website. Actual tax liability may differ depending on an individual's specific financial circumstances, allowances, tax credits, or other unique factors.
        </p>
      </div>

      {/* 3. Not Professional Tax Advice */}
      <div className="space-y-3">
        <h2 className="text-xl font-bold text-gray-900">3. Not Professional Tax Advice</h2>
        <p className="text-base text-gray-700 leading-relaxed">
          The information and calculator results provided on CalculatePKTax do not constitute professional tax, legal, accounting, or financial advice. Users should consult a qualified professional or tax advisor when they need formal guidance for their individual tax situation or compliance obligations.
        </p>
      </div>

      {/* 4. Tax Rates and Rules */}
      <div className="space-y-3">
        <h2 className="text-xl font-bold text-gray-900">4. Tax Rates and Rules</h2>
        <p className="text-base text-gray-700 leading-relaxed">
          Tax rates, slabs, exemptions, deductions, and other regulatory rules may change through government legislation and budget revisions. While CalculatePKTax aims to keep its information updated, users should verify current tax rules with official Federal Board of Revenue (FBR) sources.
        </p>
      </div>

      {/* 5. No Guarantee */}
      <div className="space-y-3">
        <h2 className="text-xl font-bold text-gray-900">5. No Guarantee</h2>
        <p className="text-base text-gray-700 leading-relaxed">
          Reasonable efforts are made to provide accurate information and dependable calculations. However, CalculatePKTax does not guarantee or warrant that every result, calculation, or piece of information will always be completely accurate, current, error-free, or applicable to every individual scenario.
        </p>
      </div>

      {/* 6. External Sources and Links */}
      <div className="space-y-3">
        <h2 className="text-xl font-bold text-gray-900">6. External Sources and Links</h2>
        <p className="text-base text-gray-700 leading-relaxed">
          The website may reference or link to external sources and third-party websites. CalculatePKTax is not responsible for the content, accuracy, availability, or privacy policies of any external websites linked from our platform.
        </p>
      </div>

      {/* 7. User Responsibility */}
      <div className="space-y-3">
        <h2 className="text-xl font-bold text-gray-900">7. User Responsibility</h2>
        <p className="text-base text-gray-700 leading-relaxed">
          Users are solely responsible for reviewing calculator results, verifying supporting information, and ensuring compliance with all applicable tax laws before making financial, tax filing, or other professional decisions.
        </p>
      </div>

      {/* 8. Contact */}
      <div className="space-y-3 pt-4 border-t border-gray-200">
        <h2 className="text-xl font-bold text-gray-900">8. Contact</h2>
        <p className="text-base text-gray-700 leading-relaxed">
          For any questions or clarifications regarding this Disclaimer, please contact us at:
        </p>
        <p className="text-base font-medium">
         <a
  href="https://mail.google.com/mail/?view=cm&fs=1&to=contactnowmuhammadharis@gmail.com"
  target="_blank"
  rel="noopener noreferrer"
  className="text-[#1D4ED8] hover:underline font-medium"
>
  contactnowmuhammadharis@gmail.com
</a>
        </p>
      </div>

    </div>
  );
}